import {test,expect} from '@playwright/test';
import {analyzeComparison} from '../../src/domain/analyze-comparison';
import {fixtureScans,fixtureRoadEvidence,TUTORIAL_CHECKED_AT} from '../../src/data/activity-fixtures';
import {sampleRouteOptions} from '../../src/providers/routes';
test('hospital colour, 24-hour status and opening-hours details fit a narrow phone screen',async({page})=>{
 const samples=sampleRouteOptions('AEOS','normal');
 const result=analyzeComparison(samples,p=>fixtureScans(p,'normal'),TUTORIAL_CHECKED_AT,fixtureRoadEvidence(samples,'normal'));
 const data={routes:samples.map(r=>({...r,source:'google',geometryKind:'provider'})),analyses:result.analyses.map(a=>({...a,source:'live',places:[{...a.places[0],id:'hospital-24',name:'Test 24-hour hospital',categories:['hospital'],schedule:{currentWeek:['Monday: Open 24 hours'],regularWeek:['Monday: Open 24 hours'],specialDates:[]},hours:{state:'open',closingSoon:false,minutesUntilClose:null,basis:'current',open24Hours:true}}]})),comparison:result.comparison,checkedAt:TUTORIAL_CHECKED_AT,activityStatus:'complete',notices:[],attributions:[],usage:{remainingComparisons:1}};
 await page.setViewportSize({width:320,height:720});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.route('https://**/*',r=>r.abort());
 await page.route('**/api/**',r=>r.fulfill({json:r.request().url().endsWith('/compare')?data:{ready:true}}));
 await page.goto('/');
 await page.getByRole('button',{name:'Live routes',exact:true}).click();
 await page.getByRole('button',{name:'Compare night routes'}).click();
 await page.getByRole('button',{name:'Confirm and compare'}).click();
 await expect(page.locator('.pin-legend').getByText('Hospitals',{exact:true})).toBeVisible();
 await expect(page.locator('.pin-legend span').filter({hasText:'Hospitals'}).locator('i')).toHaveCSS('background-color','rgb(167, 139, 250)');
 await expect(page.locator('.map-place-controls input[type=checkbox]')).toHaveCount(0);
 await expect(page.getByText('Places shown on this map',{exact:true})).toHaveCount(0);
 const help=page.locator('.help-details').filter({has:page.getByText('Help points on selected route',{exact:true})});
 await help.locator('summary').click();
 await expect(help).toContainText('Test 24-hour hospital');
 await expect(help).toContainText('Open 24 hours');
 const gap=await help.evaluate(el=>el.getBoundingClientRect().top-el.previousElementSibling!.getBoundingClientRect().bottom);
 expect(gap).toBeGreaterThanOrEqual(16);
 await page.getByText('Opening times and closed days',{exact:true}).click();
 const item=page.locator('.shop-hours-item').filter({hasText:'Test 24-hour hospital'});
 await item.locator('summary').click();
 await expect(item).toContainText('Open 24 hours');
 await expect(item).toContainText('outpatient');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await item.screenshot({path:'tmp/browser-regression/hospital-24-hours.png'});
});
