import {test,expect} from '@playwright/test';
const result={suggestions:[{id:'palace',title:'Bengaluru Palace',address:'Vasanth Nagar, Bengaluru',straightDistanceMeters:6500},{id:'grounds',title:'Bengaluru Palace Grounds',address:'Palace Road, Bengaluru',straightDistanceMeters:6300}]};
const status={ready:true,searchEnabled:true,searchPreviewEnabled:true,activityEnabled:true,scoringEnabled:true};
test.beforeEach(async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.route('https://**/*',r=>r.abort());await page.route('**/api/status',r=>r.fulfill({json:status}));await page.goto('/');await page.getByRole('button',{name:'Live routes',exact:true}).click();});
test('typing suggests places then shows provider driving estimates and selects a destination',async({page})=>{
 let calls=0,body:any;await page.route('**/api/places/suggest',r=>{calls++;return r.fulfill({json:result});});await page.route('**/api/places/preview',r=>{body=r.request().postDataJSON();return r.fulfill({json:{checkedAt:new Date().toISOString(),estimates:[{id:'palace',available:true,distanceMeters:7200,durationSeconds:1260},{id:'grounds',available:true,distanceMeters:6900,durationSeconds:1200}]}});});await page.route('**/api/places/resolve',r=>r.fulfill({json:{coordinate:{latitude:13.0035,longitude:77.5891},address:'Palace Road'}}));
 await page.locator('.place-field.destination').click();await page.getByLabel('Search places').fill('be');await page.waitForTimeout(850);expect(calls).toBe(0);await page.getByLabel('Search places').fill('bengaluru');await expect(page.getByRole('region',{name:'Google place results'})).toContainText('7.2 km · 21 min');expect(calls).toBe(1);expect(body.direction).toBe('from-anchor');expect(body.anchor.latitude).toBeCloseTo(13.0628268);await expect(page.locator('.search-trip-context')).toContainText('From AEOS');
 await page.getByRole('button',{name:/Bengaluru Palace Vasanth Nagar/}).click();await expect(page.locator('.place-field.destination')).toContainText('Bengaluru Palace');
});
test('origin searches show travel toward the chosen destination in both themes',async({page})=>{
 let direction='';await page.route('**/api/places/suggest',r=>r.fulfill({json:result}));await page.route('**/api/places/preview',r=>{direction=r.request().postDataJSON().direction;return r.fulfill({json:{checkedAt:new Date().toISOString(),estimates:[{id:'palace',available:true,distanceMeters:12100,durationSeconds:2100},{id:'grounds',available:true,distanceMeters:12000,durationSeconds:1980}]}});});await page.getByRole('button',{name:'Open settings'}).click();await page.getByText('Mono Light',{exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();await page.locator('.place-field').first().click();await page.getByLabel('Search places').fill('bengaluru');await expect(page.locator('.search-travel').first()).toContainText('12.1 km · 35 min');expect(direction).toBe('to-anchor');await expect(page.locator('.search-trip-context')).toContainText('To Manyata');await page.locator('.sheet').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'talks/screenshots/search-preview/01-light-search-mocked.png'});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:'talks/screenshots/search-preview/02-dark-search-mocked.png'});await page.setViewportSize({width:320,height:640});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('unavailable estimates do not turn straight-line distance into drive time or block selection',async({page})=>{
 await page.route('**/api/places/suggest',r=>r.fulfill({json:result}));await page.route('**/api/places/preview',r=>r.fulfill({status:429,json:{message:'Preview cap reached'}}));await page.locator('.place-field.destination').click();await page.getByLabel('Search places').fill('bengaluru');await expect(page.getByText('Driving estimates unavailable. You can still choose a place.')).toBeVisible();await expect(page.locator('.search-result').first()).toContainText('6.5 km straight-line distance');await expect(page.locator('.search-result').first()).toBeEnabled();await expect(page.locator('.search-result').first()).not.toContainText(/\d+ min/);
});
test('editing a query clears old suggestions and cancels their pending travel preview',async({page})=>{
 let previews=0;await page.route('**/api/places/suggest',r=>r.fulfill({json:r.request().postDataJSON().query==='bengaluru'?result:{suggestions:[]}}));await page.route('**/api/places/preview',r=>{previews++;return r.fulfill({status:503,json:{}});});await page.locator('.place-field.destination').click();await page.getByLabel('Search places').fill('bengaluru');await expect(page.locator('.search-result')).toHaveCount(2);await page.getByLabel('Search places').fill('manyata');await expect(page.locator('.search-result')).toHaveCount(0);await expect(page.getByText(/No matching places found/)).toBeVisible();await page.waitForTimeout(1000);expect(previews).toBe(0);
});
