import {config as loadEnv} from 'dotenv';
import {createGeoapifyServer} from './geoapify-app';
import {readGeoConfig} from './geoapify-config';
import {GeoRedisBudget} from './geoapify-budget';
import {serveGeoWeb} from './geoapify-web';
process.env.TZ='Asia/Kolkata';
loadEnv({path:'.local/geoapify.env',quiet:true});
const config=readGeoConfig();
if(!config.key)throw new Error('Set the server-side GEOAPIFY_API_KEY.');
const budget=config.redisUrl?new GeoRedisBudget(config.redisUrl,config.redisToken,config.redisKey):undefined;
if(budget)await budget.initialize();
const app=await createGeoapifyServer(config.key,config,budget);
if(config.serveWeb)await serveGeoWeb(app);
await app.listen({host:config.host,port:config.port});
console.log(`Nightwise Geoapify ${config.serveWeb?'website and API':'API'} listening on port ${config.port}; usage storage: ${budget?'Upstash':'local'}.`);
for(const s of ['SIGINT','SIGTERM'] as const)process.once(s,()=>{void app.close().then(()=>process.exit(0));});
