from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'src/App.tsx'
s=p.read_text(encoding='utf-8')
start=s.index("    {modal === 'evidence'")
end=s.index("    {modal === 'handoff'",start)
s=s[:start]+'''    {modal === 'evidence' && selectedRoute && selectedAnalysis && <Sheet title="A closer look at this route" onClose={() => setModal(null)}><span className="sample-badge">Calculated from sample observations</span><p className="evidence-lead">{selectedRoute.label} · {minutes(selectedRoute)} minutes<br/><span>Here’s what the evidence can tell us.</span></p>{!selectedAnalysis.coreComparable&&<div className="unknown-explanation"><Illustration name="evidence-unknown" compact/><p>Some evidence is missing. Unassessed areas are unknown, not low activity.</p></div>}<ActivityStrip analysis={selectedAnalysis}/><dl className="evidence-rows"><div><dt>Observed places listed as open</dt><dd>{selectedAnalysis.openPlaces ?? 'Unavailable'}</dd></div><div><dt>Observed places listed as closed</dt><dd>{selectedAnalysis.closedPlaces ?? 'Unavailable'}</dd></div><div><dt>Places with unknown hours</dt><dd>{selectedAnalysis.unknownHours ?? 'Unavailable'}</dd></div><div><dt>Potential help listings open now</dt><dd>{selectedAnalysis.potentialHelpPoints ?? 'Unavailable'}</dd></div><div><dt>Listed places closing soon</dt><dd>{selectedAnalysis.closingSoon ?? 'Unavailable'}</dd></div><div><dt>Longest low-activity stretch</dt><dd>{formatMeters(selectedAnalysis.longestLowActivityMeters)}</dd></div><div><dt>Scan coverage by distance</dt><dd>{Math.round(selectedAnalysis.scanCoverage*100)}%</dd></div><div><dt>Activity evidence coverage</dt><dd>{Math.round(selectedAnalysis.activityCoverage*100)}%</dd></div><div><dt>Known opening hours</dt><dd>{selectedAnalysis.openPlaces===null?'Unavailable':`${Math.round(selectedAnalysis.hoursCoverage*100)}%`}</dd></div><div><dt>Illustrative check time</dt><dd>9 Sep · 8:30 pm IST</dd></div></dl><div className="evidence-footnotes"><p>Counts are distinct observed listings, not a census. The gap estimate comes from samples about 200 m apart and is not a surveyed street measurement.</p><p>Lighting, road classification and crime are not measured. Potential help categories do not verify access, staff or assistance.</p>{selectedAnalysis.limitations.map(text=><p key={text}>{text}</p>)}<p>Opening hours describe the sample check time, not a forecast. A numeric activity score is withheld while the model remains uncalibrated.</p></div><button className="secondary-button" onClick={() => setModal(null)}>Back to routes</button></Sheet>}
''' + s[end:]
s=s.replace('<Clock3 size={17} /> Leave now','<Clock3 size={17} /> 8:30 pm · sample')
s=s.replace('Routes, durations, distances and activity are illustrative. Only the AEOS destination pin comes from the supplied place link.', 'Routes, durations and place observations are illustrative. Activity counts and comparisons are calculated from those sample observations. Only the AEOS destination pin comes from the supplied place link.')
s=s.replace('<h3>Your privacy</h3>','<h3>How comparisons work</h3><p>We sample along each path, count each observed place once and keep unknown sections separate. Extra time is shown alongside evidence. A substantial detour or incomplete data prevents an automatic activity recommendation.</p><h3>Your privacy</h3>')
p.write_text(s,encoding='utf-8')
