from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'src/App.tsx'
s=p.read_text(encoding='utf-8')
start=s.index("    {modal === 'origin'")
end=s.index("    {modal === 'evidence'",start)
s=s[:start]+'''    {modal === 'origin' && <Sheet title="Choose your starting point" onClose={() => setModal(null)}><p className="sheet-intro">Two Bengaluru journeys prepared for the tutorial.</p><label className="search-label" htmlFor="origin-search">Find a tutorial starting point</label><input id="origin-search" className="origin-search" value={originQuery} onChange={e=>setOriginQuery(e.target.value)} placeholder="Manyata or Sahakar Nagar" autoComplete="off"/>{origins.filter(place=>place.toLowerCase().includes(originQuery.trim().toLowerCase())).map(place => <button className="origin-option" key={place} onClick={() => { setOrigin(place); cancel(); setModal(null); setOriginQuery(''); }}><span className="place-icon"><MapPin size={19} /></span><span><strong>{place}</strong><small>Bengaluru, India</small></span>{origin === place ? <Check size={19} /> : <ChevronRight size={18} />}</button>)}{!origins.some(place=>place.toLowerCase().includes(originQuery.trim().toLowerCase()))&&<p className="settings-helper" role="status">No prepared starting point matches. Try Manyata or Sahakar Nagar.</p>}<p className="settings-helper">This searches the two tutorial presets. Live place search connects later. Exact gates and road entrances will be checked before the live demonstration.</p></Sheet>}
    {modal === 'destination' && <Sheet title="Your AEOS destination" onClose={()=>setModal(null)}><span className="place-icon large"><Building2 size={25}/></span><p className="evidence-lead">AEOS<br/><span>Bengaluru, India</span></p><p>The office pin is taken from your supplied Google Maps link. The exact road entrance still needs a local check.</p><dl className="evidence-rows"><div><dt>Latitude</dt><dd>{AEOS.latitude}</dd></div><div><dt>Longitude</dt><dd>{AEOS.longitude}</dd></div></dl><button className="primary-button" onClick={()=>setModal(null)}>Use this destination <Check size={18}/></button></Sheet>}
''' + s[end:]
s=s.replace('{selectedRoute.evidence.openPlaces}', "{selectedRoute.evidence.openPlaces ?? 'Not assessed'}").replace('{selectedRoute.evidence.potentialHelpPoints}', "{selectedRoute.evidence.potentialHelpPoints ?? 'Not assessed'}")
s=s.replace("~{selectedRoute.evidence.longestLowActivityMeters! >= 1000 ? '1 km' : selectedRoute.evidence.longestLowActivityMeters + ' m'}", "{selectedRoute.evidence.longestLowActivityMeters === null ? 'Not assessed' : `~${selectedRoute.evidence.longestLowActivityMeters} m`}")
s=s.replace('<p>Google Maps will calculate a current route', '<p className="selected-handoff">Selected: {selectedRoute?.label} · {selectedRoute ? minutes(selectedRoute) : 0} min in this sample</p><p>Google Maps will calculate a current route')
s=s.replace('<h3>About this tutorial</h3>', '<Illustration name="activity-explained-v2"/><h3>About this tutorial</h3>')
s=s.replace('autoPlay muted playsInline aria-hidden="true"', 'autoPlay muted playsInline poster="/assets/launch/nightwise-launch-poster.png" aria-hidden="true"')
p.write_text(s,encoding='utf-8')
